### ISSUE TITLE
oAuth Example

### ISSUE THREAD

**Issue by objectiveSee** [shernshiou/node-uber#10]
Can somebody provide an example of how to authorize? I dont know what to use for redirect URL

**Comment by shernshiou** [comment]
@objectiveSee I will do that soon. Thanks

**Comment by scottdixon** [comment]
@shernshiou - thanks for the awesome library.

@objectiveSee - I created a basic example here: https://github.com/scottdixon/node-express-uber-example

**Comment by agraebe** [comment]
@shernshiou do you still need help with that? I have another sample [here](https://github.com/agraebe/Take-Me-Home-Now/blob/master/app.js)

**Comment by shernshiou** [comment]
@agraebe @scottdixon yeah help is greatly needed

**Comment by agraebe** [comment]
@scottdixon I got inspired by your example and updated the README: https://github.com/shernshiou/node-uber/blob/master/README.md. Do you have any other suggestions for improvement?

@objectiveSee I hope this will be help for you. Let us know otherwise!

**Comment by aleksdao** [comment]
@agraebe Are you aware of any issues with creating/requesting a ride?

I seem to get a 401 (unauthorized) on every uber.requests.create() call -- all other API calls requiring access_token are functioning fine.

**Comment by agraebe** [comment]
@aleksdao I'm not aware of any issues... let me double check in a few hours... Would you mind sharing your code within a new issue? And also, did you request the required scope (and enabled it for your app in the Uber Developer Dashboard)?
