### ISSUE TITLE
Legal Code

### ISSUE THREAD

**Issue by hongkongkiwi** [shernshiou/node-uber#15]
Hi there,

Just wondering if we are legally allowed to use this API? e.g. is this Uber supported or will we be at risk of getting banned?

**Comment by agraebe** [comment]
Hey Andy,

this wrapper is simply making HTTP GET/POST calls to the API endpoints exposed by Uber. So, yeah, you are allowed to use it without any risk. However, by using the API you agree with the [Terms of Use of the Uber API](https://developer.uber.com/docs/terms-of-use)

**Comment by shernshiou** [comment]
Thanks @agraebe
