### ISSUE TITLE
Promotions Endpoint deprecated?

### ISSUE THREAD

**Issue by agraebe** [shernshiou/node-uber#16]
Hey @shernshiou,

I can't find a promotions endpoint and I'm assuming it's left-over from a deprecated endpoint, correct? If so, I'd create a PR removing it.

**Comment by shernshiou** [comment]
@agraebe sure you can.

**Comment by agraebe** [comment]
Great! I'm actually extending the whole module (including all existing endpoints). Will send a PR soon :)
