### ISSUE TITLE
CodeClimate: Setting Up Test Coverage

### ISSUE THREAD

**Issue by agraebe** [shernshiou/node-uber#18]
@shernshiou would you mind to either add me as an admin to this repo or follow [this](https://docs.codeclimate.com/docs/setting-up-test-coverage) instructions to enable code coverage reports for this project? Would be nice to see where we at :)

**Comment by shernshiou** [comment]
I will assign you as the admin.

**Comment by agraebe** [comment]
Thanks! Turns out, [admin level rights are only available for organization-maintained repos](https://help.github.com/articles/adding-collaborators-to-a-personal-repository/). In other words, you're the only one who could setup it up :) 

I'd vote for it. Hope you can find some time to help with it.

**Comment by shernshiou** [comment]
@agraebe yeah too bad. I tried to insert the token into .travis.yml but it doesn't work. I wonder whether the token is correct.

**Comment by agraebe** [comment]
I think I got it figured out. I'm adding some more tests to have > 90% coverage :)

**Comment by agraebe** [comment]
see latest merged PR 👍
