### ISSUE TITLE
Using ES6 with Node 4.0.0+ as engine

### ISSUE THREAD

**Issue by agraebe** [shernshiou/node-uber#30]
Right now, our tests in TravisCI cover (and pass) older versions of Node (0.10, 0.11, 0.12, iojs). I'm considering to use some ES6 features and wanted to understand you think there would be a tremendous drawback if we remove backward compatibility.

@shernshiou @puzzlehe4d

**Comment by shernshiou** [comment]
@agraebe yes that's my plan. That's the reason I am not developing in pre4.0.0 version anymore.

**Comment by agraebe** [comment]
Cool, how about we create a new branch for es6 development?
