### ISSUE TITLE
Add promise support

### ISSUE THREAD

**Issue by matts310** [shernshiou/node-uber#45]
Add support for use of promises instead of callbacks

**Comment by agraebe** [comment]
We have implemented this feature for v1.0. You can give at a shot, it's stable. Just check out the v1.0.0 branch :) 

We used Bluebird for the premises, which appends "Async"  to all async promisified methods. For instance, ``user.getProfile`` becomes ``user.getProfileAsync``. Please find more details in the [updated Readme](
