### ISSUE TITLE
Where to install node-uber at?

### ISSUE THREAD

**Issue by rolinger** [shernshiou/node-uber#5]
This might seem like a dumb question, but this is my first node_module I have used or am using.  

* I installed node-uber with: "npm install node-uber --save-dev"
* and it installed to:  \dev\appName\node_modules\node-uber.
* But when I add the code to my script in \dev\appName\www\js\index.js : var Uber= require('node-uber') ; 

i get this error: Uncaught ReferenceError: require is not defined.  

'node-uber' is listed in my devDependencies section of my package.json file.  

What am I doing wrong?

**Comment by shernshiou** [comment]
You should install with '--save' but it makes no differences.
