### ISSUE TITLE
Update to API v1.2 endpoints

### ISSUE THREAD

**Issue by agraebe** [shernshiou/node-uber#51]
Uber recently [announced](https://developer.uber.com/docs/riders/change-log) v1.2 endpoints for the Rides API. The following changes would be required to upgrade:
1. API base URL would need to reflect the version bump: ``https://api.uber.com/v1.2/``. [Sample endpoint](https://developer.uber.com/docs/riders/references/api/v1.2/me-get). 
2. A new ride request flow for upfront prices should be implemented, as [described here](https://developer.uber.com/docs/riders/ride-requests/tutorials/api/best-practices#upfront-fares)
3. All usage of rate limiting headers should be removed. [The headers are deprecated with v1.2](https://medium.com/uber-developers/announcing-riders-api-1-2-featuring-upfront-fares-ride-promotions-and-improved-dev-docs-7745135ca33f#.da7wwtnm8). A new endpoint to meet the needs will be created. Here are the impacted headers: `X-Rate-Limit-Limit`, `X-Rate-Limit-Remaining`, `X-Rate-Limit-Reset`.

**Comment by Rulikkk** [comment]
@agraebe could you please let me know if there is any timeline for v1 API disabling?

**Comment by agraebe** [comment]
@Rulikkk there is no official timeline to deprecate v1 (yet)

**Comment by staplen** [comment]
@agraebe any update on v1.2 support? Still looking for help on the implementation?

**Comment by agraebe** [comment]
@staplen we're always looking for help. I still didn't had time to focus on this!

**Comment by agraebe** [comment]
fixed with #67
