### ISSUE TITLE
how to use tracking api?

### ISSUE THREAD

**Issue by suriyaJaay** [shernshiou/node-uber#52]
hi 
am trying create to app for sales. my is made on  nodejs with angularjs .i just want track field person like tracking cab in real time. so i decided to use uber tracking api only..!!

is that possible to use like that?
does uber has separate api for tracking purpose only.?

kindly explain flow of the process and how to make use of it..

thank you Team

**Comment by agraebe** [comment]
There is no such thing as a tracking API. It seems you're looking for webhooks. Please see the Trip Experiences documentation: https://developer.uber.com/docs/trip-experiences

This wrapper does not support consumption of webhooks. However, if your users authorize your app, you can get their current trip status. Please read the README: https://github.com/shernshiou/node-uber#get-current-request
