### ISSUE TITLE
Support for drivers api needed

### ISSUE THREAD

**Issue by openpathgit** [shernshiou/node-uber#55]
Is there any plans to add support for the drivers api? We are using it now and would love to have the support

**Comment by agraebe** [comment]
Let's put this on the roadmap for v.1.1 - want to take it and implement the features?

**Comment by dustinwhittle** [comment]
Can you add support for the Uber Driver APIs? Here is an [example diff from the python sdk](https://github.com/uber/rides-python-sdk/pull/45/files#diff-f28d240a7be85035693dfe494cc123c6).

**Comment by agraebe** [comment]
Fixed with #63
