### ISSUE TITLE
Receiving 3 failing errors during Authentication

### ISSUE THREAD

**Issue by rolinger** [shernshiou/node-uber#6]
After MUCH learning I finally am implementing node-uber the correct way.  Apologies for the many reported issues previously - they were not your app and were my fault.  

That being said, in the /test folder I have replaced your "var key" in index.js and key.json info with my own registered uber keys/tokens, and am now getting the following errors.   Please advise:

[08:48:38] Using gulpfile ~\dev\WHIPSTER\node_modules\node-uber\gulpfile.js
[08:48:38] Starting 'test'...

  Uber client general test
    √ should load the key from a key.json
    √ should initiate Uber client with the key

  OAuth2 authorization methods
    OAuth2 authorization url
      √ generate OAuth2 correct authorization url
      √ should return error if scope is not an array
      √ should return error if scope is not an empty array
    Exchange authorization code into access token
createCredentials() is deprecated, use tls.createSecureContext instead
      √ should able to get access token and refresh token using authorization code
      √ should able to get access token and refresh token using refresh token
      √ should return error if there is no authorization_code or refresh_token

  Products Resource
    Products List
      1) should list down all the product types
      √ should return error if there is no required params

  Estimates Resource
    Price Estimates
      2) should list all the price estimates from server
      √ should return error if there is no required params
    Time Estimates
      3) should list all the price estimates from server
      √ should return error if there is no required params

  User Resource
    User Profile
      √ should get user profile after authentication
      √ should get user profile after authentication by explicitly passing access token
      √ should return invalid access token error when no token found

  14 passing (125ms)
  3 failing

  1) Products Resource Products List should list down all the product types:
     Uncaught AssertionError: expected [Error: Nock: No match for request GET https://api.uber.com/v1/products?server_token=XXXXXXPaPcEE0cHb
whKiF_sl_ZUYvEHHO_f6U6dr&latitude=3.1357&longitude=101.688 ] to not exist

  2) Estimates Resource Price Estimates should list all the price estimates from server:
     Uncaught AssertionError: expected [Error: Nock: No match for request GET https://api.uber.com/v1/estimates/price?server_token=XXXXXXPaP
cEE0cHbwhKiF_sl_ZUYvEHHO_f6U6dr&start_latitude=3.1357&start_longitude=101.688&end_latitude=3.0833&end_longitude=101.65 ] to not exist

  3) Estimates Resource Time Estimates should list all the price estimates from server:
     Uncaught AssertionError: expected [Error: Nock: No match for request GET https://api.uber.com/v1/estimates/time?server_token=XXXXXXPaPc
EE0cHbwhKiF_sl_ZUYvEHHO_f6U6dr&start_latitude=3.1357&start_longitude=101.688&end_latitude=3.0833&end_longitude=101.65 ] to not exist

**Comment by shernshiou** [comment]
Actually, the test script is for developer. It is not meant to be tested. I have included sample code at the example folder as per requested. Can you try the code there?
