### ISSUE TITLE
Remove reminders endpoints

### ISSUE THREAD

**Issue by agraebe** [shernshiou/node-uber#68]
The ride reminders endpoints are not documented anymore. Removing them as part of #51

**Comment by agraebe** [comment]
fixed with #67

**Comment by jonterrylee** [comment]
Hi, is there any reason why reminders are no longer supported?

**Comment by agraebe** [comment]
@jonterrylee these endpoints will be deprecated at some point. There will be an official announcement and a fixed timeframe announced soon.
