### ISSUE TITLE
"request" scope is not working

### ISSUE THREAD

**Issue by Kaushick** [shernshiou/node-uber#8]
When I'm calling ```uber.getAuthorizeUrl(['request']);``` I'm getting an url. But after loging in getting an error "invalid_scope". I also tried to call the uber api directly from a cordova app, and also getting the same error. Maybe this is not your issue. I opened this issue to discuss and find the solution.

**Comment by shernshiou** [comment]
I am so sorry, I did not catch up with the newest api. I will get back to you soon.

**Comment by Kaushick** [comment]
@shernshiou,   Thanks for your response. When you will get any kind of solution or if you want give me any suggestion please let me know.

**Comment by shernshiou** [comment]
@Kaushick can you print the authorize url you get from the method for me?

**Comment by shernshiou** [comment]
Fixed by 25b0e0a332338f28999312e3c6746b4e268135cb
